[package]

name = "peg"
version = "0.2.0"
authors = [ "Kevin Mehall <km@kevinmehall.net>" ]
license = "MIT"
repository = "https://github.com/kevinmehall/rust-peg"
description = """
A parser generator built on the Parsing Expression Grammar (PEG) formalism.
"""

[[bin]]
name = "peg"
path = "src/peg.rs"

[lib]
plugin = true
name = "peg_syntax_ext"
