[workspace]
members = ["./peg-syntax-ext", "./peg-codegen", "./peg-runtime"]

[package]
name = "peg"
version = "0.6.0"
authors = [ "Kevin Mehall <km@kevinmehall.net>" ]
license = "MIT"
repository = "https://github.com/kevinmehall/rust-peg"
documentation = "https://github.com/kevinmehall/rust-peg/blob/master/README.md#readme"
description = "A simple Parsing Expression Grammar (PEG) parser generator."
keywords = ["peg", "parser", "parsing", "grammar"]
categories = ["parsing"]
readme = "README.md"

[dependencies]
peg-codegen = { path = "./peg-codegen", version = "0.6" }
peg-syntax-ext = { path = "./peg-syntax-ext", version = "0.6" }
peg-runtime = { path = "./peg-runtime", version = "0.6" }

[dev-dependencies]
trybuild = "1.0"

[[bin]]
name = "rust-peg"
path = "src/bin.rs"
test = false
bench = false

[[test]]
name = "trybuild"
path = "tests/trybuild.rs"
harness = false

[features]
trace = []
