[workspace]
members = ["./peg-syntax-ext", "./peg-tests"]

[package]
name = "peg"
version = "0.4.2"
authors = [ "Kevin Mehall <km@kevinmehall.net>" ]
license = "MIT"
repository = "https://github.com/kevinmehall/rust-peg"
description = """
A parser generator built on the Parsing Expression Grammar (PEG) formalism.
"""

[dependencies]
quote = "0.3"

[[bin]]
name = "rust-peg"
path = "src/bin.rs"
test = false
bench = false

[features]
trace = []
