[package]

name = "peg"
version = "0.1.0"
authors = [ "km@kevinmehall.net" ]

[[bin]]
name = "peg"
path = "src/peg.rs"

[lib]
plugin = true
name = "peg_syntax_ext"

[[bin]]
name = "test_arithmetic"
path = "examples/test_arithmetic.rs"
